name: Build EXE FIX
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build completo
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        pyinstaller --onedir --name zoffline --add-data "cdn;cdn" --add-data "data;data" --add-data "ssl;ssl" --add-data "storage;storage" --add-data "storage;storage" --hidden-import=google.protobuf standalone.py
    - uses: actions/upload-artifact@v4
      with:
        name: zoffline-completo
        path: dist/zoffline
